9oormthon-univ-swu/2024_FINAL_STARCAPSULE_BE

- src/main/java/goormthonuniv/swu/starcapsule/global/base/dto/ResponseDto.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/Snowball.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballController.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballService.java
추후에 프론트엔드랑 경로 협의 한 다음에 수정해야 함.
> Feat: snowball 이름 수정

- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemory.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryController.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryService.java
> Feat: 내 기록 작성 이미지 업로드

- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestion.java
- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestionController.java
- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestionDto.java
- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestionRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestionService.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemory.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryController.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryDto.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryListDto.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryService.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryShapeDto.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/PageInfo.java
> Feat : 나의 추억 공개일 전, 후 조회

- src/main/java/goormthonuniv/swu/starcapsule/calendar/CalendarController.java
- src/main/java/goormthonuniv/swu/starcapsule/memory/MemoryRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/memory/MemoryService.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryController.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryService.java
> Feat : 캘린더 추억 퍼즐 조회

- src/main/java/goormthonuniv/swu/starcapsule/calendar/CalendarController.java
- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestionController.java
- src/main/java/goormthonuniv/swu/starcapsule/memory/MemoryRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/memory/MemoryService.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryService.java
> Feat : 캘린더 날짜별 추억 조회

- src/main/java/goormthonuniv/swu/starcapsule/calendar/CalendarController.java
snowball id parameter 삭제
프론트에서 token값 넘겨주면 회원정보 조회 후 user의 snowball 조회하는 로직
> Fix: parameter snowball id 제거

- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestionService.java
- src/main/java/goormthonuniv/swu/starcapsule/memory/Memory.java
- src/main/java/goormthonuniv/swu/starcapsule/memory/MemoryResponse.java
- src/main/resources/application.properties
> fix : TimeZone 일괄 수정 및 생성일 추가

- src/main/java/goormthonuniv/swu/starcapsule/calendar/CalendarController.java
- src/main/java/goormthonuniv/swu/starcapsule/memory/MemoryResponse.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryDto.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/MemoryDto.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballMemoryResponse.java
> fix : toSnakeCase

- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemory.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryController.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/myMemory/MyMemoryService.java
> fix: 1일 1추억 작성으로 제한

- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballController.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballService.java
> fix : 스노우볼 조회시 접근권한 분리

- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballMemoryResponse.java
> fix : 데이터 분리 및 최적화

- src/main/java/goormthonuniv/swu/starcapsule/calendar/CalendarController.java
> fix : getMySnowball로 id값 불러오기

- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestionController.java
> fix : 내 기록있을 경우 오늘의 질문 400 에러 반환

- src/main/java/goormthonuniv/swu/starcapsule/calendar/CalendarController.java
- src/main/java/goormthonuniv/swu/starcapsule/memory/MemoryRepository.java
1. T/F 에 Memory를 Snowball을 조회하지 못해서 생기는 문제 해결
2. 반환하는 DTO가 달라 알맞은 DTO로 변경
3. Memory 조회시 해당하는 날짜에 맞게 조회되지 않는 문제가 생겨 해결
> fix : 캘린더 조회시 자잘한 문제 해결

- src/main/java/goormthonuniv/swu/starcapsule/global/config/oauth/WebOAuthSecurityConfig.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/BasicSnowballResponse.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/PaginationSnowballResponse.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballController.java
> Fix: 스노우볼 조회 API 분리 및 스노우볼 엔드포인트 접근 허용을 위한 보안 설정 업데이트

- src/main/java/goormthonuniv/swu/starcapsule/snowball/MemoryDto.java
> fix : 스노우볼 이름으로 반환

- src/main/java/goormthonuniv/swu/starcapsule/memory/MemoryController.java
> fix : 인증토큰 추가

- src/main/java/goormthonuniv/swu/starcapsule/global/config/jwt/AccessTokenProvider.java
- src/main/java/goormthonuniv/swu/starcapsule/global/config/jwt/RefreshTokenProvider.java
- src/main/java/goormthonuniv/swu/starcapsule/global/config/jwt/TokenProvider.java
- src/main/java/goormthonuniv/swu/starcapsule/refreshToken/RefreshTokenRepository.java
- src/main/java/goormthonuniv/swu/starcapsule/user/UserService.java
- src/main/resources/application.properties
> Feat : 액세스 토큰 갱신을 위한 새로 고침 토큰 관리 로직 추가

- src/main/java/goormthonuniv/swu/starcapsule/calendar/CalendarController.java
> Fix: 퍼즐 내 기록이 있을 경우 True 반환

- src/main/java/goormthonuniv/swu/starcapsule/dailyQuestion/DailyQuestionDto.java
> Fix: 프론트엔드 dayjs에 맞춰 형식 변경

- src/main/java/goormthonuniv/swu/starcapsule/snowball/Snowball.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballDto.java
- src/main/java/goormthonuniv/swu/starcapsule/snowball/SnowballService.java
> Fix: UID값 안넘어가는 거 수정

- src/main/java/goormthonuniv/swu/starcapsule/global/config/oauth/WebOAuthSecurityConfig.java
> Fix: CORS 에러 처리
